config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to:'pages#about'
  resources :articles
  get 'signup', to:'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
belongs_to :user
 validates :title, presence: true, length: {minimum:2, maximum:1000000}
 validates :description, presence: true, length: {minimum:2, maximum:2000000}
end

app/models/user.rb
class User < ApplicationRecord
before_save { self.email = email.downcase }
has_many :articles
validates :username, presence: true,
                    uniqueness: { case_sensitive: false}, 
                    length: {minimum: 3, maximum: 25}
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
                uniqueness: { case_sensitive: false}, 
                length: { maximum: 105 },
                format:  {with: VALID_EMAIL_REGEX}


 has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show
    end
    

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if  @article.save
          flash[:notice] = "Article was created successfully."
          redirect_to @article
        else
            render 'new'
        end
    end
    
    def update
        if  @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
             render 'edit'
        end  
    end

    def destroy
        @article.destroy
        redirect_to articles_path

    end


    private
    def set_article
        @article = Article.find(params[:id])
    end

    
    def article_params
      params.require(:article).permit(:title,:description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @articles = @user.articles

    end
    def index
        @users = User.all
      end

    def new
        @user = User.new
    end

    def create
     @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
     @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account is succefully updated"
            redirect_to @user
        else
         render 'edit'
        end
    end

    private
    def user_params
    params.require(:user).permit(:username, :email, :passsword)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="container min-vh-100">

<% @articles.each do |article| %>
  
  <div class="row justify-content-md-center">
   <div class="col-8 mt-4">
    <div class="card text-center border-dark shadow mb-5 rounded">
      <div class="card-header ">
      <%= link_to article.title, article_path(article),  class: "text-primary" %>
      <p> by <%= article.user.username %>
      </div>
      <div class="card-body">
        <p class="card-text"><%= truncate(article.description, length:300) %></p>
        <%= link_to "View", article_path(article), class: "btn btn-outline-info btn-sm" %>
        <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-warning btn-sm" %>
        <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger btn-sm", method: :delete, data: {confirm: "Are you sure?"} %>
      </div>
      <div class="card-footer text-muted">
      <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at)%> ago</small> 
      </div>
    </div>
   </div>
 </div>
<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container ">
  <div class="row justify-content-center">
  <div class="col-8 ">
   <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, local: true) do |f| %>

        <div class="row mb-3 justify-content-center">
          <%= f.label :title, class: "col-2 col-form-label " %>
          <p>
          <div class="col-8">
            <%= f.text_field :title, class:"form-control",placeholder: "Title" %>
          </div>
        </div>

        <div class="row mb-3 justify-content-center ">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <p>
          <div class="col-8">
            <%= f.text_area :description, rows: 10, class:"form-control", placeholder: "Description" %>
            </div>
        </div>

        <div class="row mb-3 col-3 mx-auto">
          <%= f.submit 'Save', class: "btn btn-primary btn-lg" %>
        </div>
      <%end%>
    </div>
    <div class="mb-3">
     <%= link_to 'Return to listing', articles_path(@article), class:"row justify-content-center" %> 
     </div>
  </div>

</div>

app/views/articles/edit.html.erb
 <h1 class= "text-center mb-5">Edit Article</h1>


<%= render 'form' %>

app/views/articles/index.html.erb
 <%= render 'articles' %>  

app/views/articles/new.html.erb
<div class="container min-vh-100 ">
  <h1 class= "text-center  mb-3">Create New Article</h1>
<%= render 'form'  %>
</div>

app/views/articles/show.html.erb
  <h2 class= "text-center  "><%= @article.title %> </h2>
  <div class="container min-vh-100">
    <div class="row justify-content-md-center ">
       <div class="col-8 mt-3 ">
        <div class="card text-center shadow mb-5 rounded">
          <div class="card-body ">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          </div>
          <p><%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-warning btn-sm " %>
          <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger btn-sm", method: :delete, data: {confirm: "Are you sure?"} %>
          <div class="card-footer text-muted ">
           <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at)%> ago</small> 
          </div>
       </div>
     </div>
   </div>
 </div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-1 bg-dark text-white ">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Elli", "https://github.com/ellipapaioannou1", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">

  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <div>
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>  

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm">
 <div class="container-fluid">
   <%= link_to "Blog", root_path, class: "navbar-brand", id: "logo" %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
              <ul class="dropdown-menu">
                <%= link_to "View All Articles",articles_path, class: "dropdown-item" %>
                <li><hr class="dropdown-divider"></li>
                <%= link_to "Create New Article",new_article_path, class: "dropdown-item" %>
              </ul>
          </li>
         <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
         </li>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Coding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/pages/about.html.erb
<h3>This is the about page</h3>

<p>
<%= link_to 'Listing', articles_path(@article) %> <p>
<p>
<%= link_to 'Home page', root_path %> <p>

app/views/pages/home.html.erb
<div class="jumbotron text-center text-black">
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %> 
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>The following errors prevented the <%= obj.class.name.downcase %> from being saved</strong>
    <ul> 
    <% obj.errors.full_messages.each do |msg| %> 
      <li><%= msg %></li> 
    <% end %> 
    </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
   <div class="col-10">
    <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, local: true) do |f| %>

        <div class="row mb-3 justify-content-center">
          <%= f.label :username, class: "col-2 col-form-label " %>
          <p>
          <div class="col-8">
            <%= f.text_field :username, class:"form-control",placeholder: "Enter username" %>
          </div>
        </div>

        <div class="row mb-3 justify-content-center ">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <p>
          <div class="col-8">
            <%= f.email_field :email, class:"form-control", placeholder: "Enter email" %>
            </div>
        </div>

        <div class="row mb-3 justify-content-center ">
        <%= f.label :password, class: "col-2 col-form-label" %>
        <p>
        <div class="col-8">
          <%= f.password_field :password, class:"form-control", placeholder: "Create your password" %>
          </div>
      </div>

        <div class="row mb-3 col-3 mx-auto">
          <%= f.submit(@user.new_record? ? 'Sign Up' : "Update account", class: "btn btn-success btn-lg") %>
        </div>
      <%end%>
    </div>
    <div class="mb-3">
     <%= link_to 'Return to listing', articles_path(@article), class:"row justify-content-center" %> 
     </div>
  </div>

</div>

app/views/users/edit.html.erb
<h1 class= "text-center mt-4">Edit your profile</h1>
<%= render 'form'  %>

app/views/users/index.html.erb
<div class="container min-vh-100">

<h1 class="text-center">Users</h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center border-dark shadow mb-5 rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-info btn-sm" %>
            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-warning btn-sm" %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/users/new.html.erb
 <h1 class= "text-center mt-4">Sign Up</h1>
 <%= render 'form'  %>
 

app/views/users/show.html.erb
<h1 class= "text-center mt-4"><%= @user.username %>'s Profile</h1>

 